title = "pg999w's blog"

description = "My life, experience and knowledge"

base_url = "https://blog.pg999w.top/"
compile_sass = true
generate_feed = true
feed_filename = "rss.xml"

theme = "even"

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
# even configs
even_title = "pg999w's blog"

even_menu = [
    {url = "$BASE_URL/rss.xml", name = "RSS"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
    #{url = "$BASE_URL/nanoblog", name = "Nanoblog"},
]

katex_enable = true
katex_auto_render = true
even_google_analytics = "UA-134598918-1"

# hyde configs
hyde_links = [
    {url = "https://google.com", name = "Google.com"},
    {url = "/tags", name = "Tags"},
]

# feather configs
feather_header_image = "/cover.jpg"
